#!/usr/bin/python3
# -*- coding: utf-8 -*-
import nltk
from textblob.classifiers import NaiveBayesClassifier
from  dao.jabuti import Jabuti
 
def analiseJabuti(id_pessoa,texto,fase):
    

    train = [

    ('Era uma vez um reino distante, perdido no meio de uma floresta. Lá, num castelo enorme, vivia um rei muito bondoso, que governava suas terras com justiça, sabedoria e generosidade. Com a rainha, ele dava longos passeios aos domingos quando visitavam os súditos, ouvindo suas queixas, solucionando conflitos e auxiliando os pobres, as viúvas e os doentes.', 'socializado'),
    ('O rei então decretou duas semanas inteiras de festas. Libertou prisioneiros, repartiu alimentos, aboliu impostos e abriu as fronteiras para que os outros povos pudessem compartilhar a sua imensa alegria.','socializado'),
    ('Coisa mais feia é o pombinho que nasceu há pouco. A pele escura, frouxa, sobra no corpo como pijama de irmão maior. Penas, nem pensar. As asas pequenas, a barriguinha gorda, as costelas aparecendo, as veias, ou o que seja que vai azulando por baixo da pele, tudo parece ainda por terminar. Mas o pior é a cabeça. Grande demais para o corpo - acho que combinaria com a pele se o esqueleto todo fosse maior - , desequilibrada sobre o pescoço magro, com um bico fino e comprido e dois olhos enormes, dois olhos saltados chegando à vida antes de todo o resto, ansiosos e meio cegos. Assim eram os dois. E eu os amei imediatamente.','socializado'),
    ('Os meus pais me deram um nome mais difícil de ser pronunciado. Ninguém sabe pronunciá-lo. No começo não gostava nada desse nome, mas depois os meus pais começaram a me explicar onde tinham ouvido o som no que seria o meu nome, o porquê de me chamarem assim, as histórias, as lendas, as chuvas que estavam atrás de poucas letras. Não o ouviram na televisão nem no rádio. Leram nos livros. Os livros, sim, eles falavam claro -mais ou menos... porque não entendia muito deles-','egocentrico'),
    ('Entrou na aula, um dia, com muito vento e muito barulho fora das janelas, uma professora nova, com uma cara de velha antipática e os olhos pesados como de alguém que nunca tinha dormido. Todo mundo dizia que era a mestra Doroteia. Mestra de quê? De desenho? Não acredito! Uma mestra de desenho? Podia, por fim, aprender a desenhar, e o ar ia entrar nos meus pulmões, no meu estômago, na minha cabeça!', 'intermediario'),
    ('Quando o sol acorda no céu das savanas, uma luz fina se espalha sobre a vegetação escura e rasteira. O dia aquece enquanto os homens lavam a terra e as mulheres cuidam dos afazeres domésticos e das crianças. Ao anoitecer, tudo volta a se encher de vazio, e o silêncio negro se transforma num ótimo companheiro para compartilhar histórias.','socializado'),
    ('Uma vez Obax contou ter visto cair do céu uma chuva de flores. - Nossa, e você se molhou? - caçoaram as crianças. - Onde foi isso? - duvidaram os mais velhos.- Calma, gente, é por isso que ela está tão cheirosa - disse a mãe, abraçando a filha', 'socializado'),
    ('Depois daquele dia, todos passaram a prestar atenção nas histórias de Obax. Ela cresceu forte como o baobá, e na sua chuva de lembranças estava Nafisa, seu grande amigo. Hoje, quem se encosta no tronco dessa árvore sagrada procurando repouso é capaz até de sonhar com suas aventuras.','intermediario'),
    ('Ele abriu somente um buraco no coco, mas umas coisas miúdas saíram correndo lá de dentro. Ele tapou o buraco, mas já tinham saído quatro coisas: uma Estrela uma Folhinha de Mato um Grão de Areia e uma Letra.','intermediario'),
    ('Ele navegou, navegou, navegou. Aí ele avistou no meio do mar um casco de tartaruga imenso coberto de montanhas, de desertos, de cidades. O casco era todo dividido por um desenho de linhas e em cada parte desse desenho se falava uma língua diferente.','intermediario'),
    ('O problema é que me sobraram os óculos para procurar os dois. E quando uso, não descubro o que está perto nem o que está distante. Tudo fica misturado e difícil de separar. Agora, moram em mim, num mesmo tempo, o feio e o bonito, o triste o alegre, o medo e a coragem, a partida e a chegada, o céu e a terra, o doce e o salgado. E por mais esforço que faça, não consigo arrancar de mim os óculos de procurar os dois. Insistiam em ser os meus olhos da verdade. Mas sem gostar de confusão, pedi ajuda ao seu Trindade. Ele veio, fez força e sumiu com os óculos para nunca mais.','socializado'),
    ('Agora eu lhes apresento Um grande cangaceiro Nascido em nosso país Leal e bom companheiro Para uns foi criminoso Para outros justiceiro Criado nas terras secas Vaqueiro trabalhador Cuidava de um ralo gado Com coragem e com valor Seu nome era Virgulino Mas um dia veio a dor','socializado'),
    ('Mas o glorioso cavaleiro não sabia, e nem poderia saber, que cada passo em direção à neblina misteriosa o levava a um obscuro portal, que rasgava o tecido do tempo e do espaço rumo ao futuro. Após passar pela densa nuvem, Lancelote descobriu-se em um lugar nunca visto. O calor do sol era tão forte que sua armadura branca de prata parecia antecipar-lhe as chamas do inferno. Mesmo assustado com a paisagem desértica, Lancelote continuou cavalgando. Em curto lapso de tempo, percebeu que a irascível feiticeira Morgana o havia lançado numa cruel armadilha.','socializado'),
    ('Vez uma era… era uma vez… ou melhor, vez era uma, desculpem era uma vez… agora sim! Era uma vez um menino que era muito atrapalhado o nome dele é esquisito porque foi escrito errado.','socializado'),
    ('Rorbeto estava tão nervoso que nem percebeu o chulé. Contando de um até dez contou 5 dedos por pé Olhou para a mão novamente sentindo um grande embaraço chorou um pouquinho, coitado. Pensando na mão do outro braço','intermediario'),
    ('O pai do Rorbeto, que era analfabeto, agora deixava de ser. E lembrou-se sorrindo do dia em que sua mulher deu a luz a um bebê E sorrindo falou para o filho: eu errei o seu nome. Seria Roberto. Mas o filho falou: não errou não senhor. O amor sempre faz tudo certo.','socializado'),
    ('Diabo também se apaixona. O nosso não queria mais que a moça visse seu pé redondo. Como todos os apaixonados, começou a cismar e a se atormentar. Maria Valsa não ia querer se casar com um pobre-diabo com pata de bode. Deu para andar meio agachado, para que as calças encobrissem o pé. À noite tinha de lavar e costurar a barra que ralava no chão. Sentia-se um lixo, um diabo qualquer a cerzir as calças puídas.” P. 17“Diabo também se apaixona. O nosso não queria mais que a moça visse seu pé redondo. Como todos os apaixonados, começou a cismar e a se atormentar. Maria Valsa não ia querer se casar com um pobre-diabo com pata de bode. Deu para andar meio agachado, para que as calças encobrissem o pé. À noite tinha de lavar e costurar a barra que ralava no chão. Sentia-se um lixo, um diabo qualquer a cerzir as calças puídas.','egocentrico'),
    ('O mundo está cheio de bichos que existem e bichos que não existem.Tem bicho que existe e a gente não acredita. Tem outros que a gente não acredita que não existam.No final das contas, não há tanta diferença entre um bicho que existe e um bicho que não existe. Todos os bichos existem: nas palavras dos livros e na cabeça da gente.','socializado'),
    ('O cão dos infernos tem três cabeças, garras de tigre e um rabo que é uma cobra. O nome dele é Cérbero. Fica na porta dos infernos, para não deixar ninguém sair. Até hoje, só dois homens conseguiram passar por ele e voltar. Um foi Hércules, o herói mais forte da Gŕecia, que o deixou acorrentado. E o outro, orfeu, o maior de todos os cantores: cantava tão bonito que acalmou até o cão dos infernos','intermediario'),
    ('De países distantes trouxe vestidos luxuosos para fazer de mim a mais reluzente das mulheres deste arraial. Aos olhos de brancos, negros, mulatos e pardos, tornei-me autoridade máxima. Quando vou às igrejas do Tijuco, sou carregada em liteiras por meus escravos.','intermediario'),
    ('Como as personagens desta história são palavras, nada mais natural que ela aconteça nas páginas de um dicionário. O dicionário é uma espécie de pomar. Só que as suas árvores, em vez de serem árvores de frutas, são árvores de palavras.','socializado'),
    ('No dia seguinte começaram a acontecer as coisas mais estranhas pelo mundo afora. Enquanto tomava o seu café da manhã, o Industrial teve a pior surpresa da sua vida quando abriu o jornal e leu o anúncio que mandara publicar. Bufando de raiva, telefonou imediatamente para o Publicitário: - Você é um incompetente, um irresponsáveç! Como teve a audácia de escrever, no anúncio que redigiu para a minha indústria, que os nossos produtos estão muito longe de ser os melhores do mundo?','socializado'),
    ('De agora em diante - eu aposto -, todos vocês vão prestar mais atenção no que dizem as pessoas aproveitadoras, para ver se elas estão mesmo dizendo a verdade quando prometem mundos e fundos.Sempre que vocês fizerem isso, lembrem-se de encostar bem o ouvido ao dicionário. Talvez consigam escutar lá dentro uma porção de risadinhas.','socializado'),
    ('Eu sempre gostei de ler livro de viagens, um dia me deu vontade de escrever um. Fiquei lembrando dos caminhos que eu tinha andado por esse mundo afora; acabei escolhendo dois ou três pra fazer o meu livro. Comecei então a pensar no jeito que eu ia usar pra viajar no papel, Quando no fim, eu me sentei pra escrever o livro, saiu um bilhete assim: “Prezado André Ando querendo bater papo. Mas ninguém tá a fim. Eles dizem que não têm tempo. Mas ficam vendo televisão. Queria te contar a minha vida. Dá pé? Um abraço da Raquel.”', 'egocentrico'),
    ('Acordei no meio da noite pensando no que o meu filho me disse: você é uma velha egoísta! fiquei olhando pra cara dele. Ele meio que riu e disse que tava brincando. Não adiantou: já tinha dito. E o você é uma velha egoísta já tinha me caído mal que só vendo.Que nem a pizza que eu comi outro dia, nossa! que pizza pra cair mal','egocentrico'),
    ('Já chega o tempo que eu fiquei numa gaveta, já chega o tempo que eu fiquei na tua cabeça: tudo tão fechado, tão cheio de complicação. Eu quero ir lá pra fora!! E hoje ela foi.','egocentrico'),
    ('Minha família tem três pessoas, contando eu e descontando o meu pai, que já morreu.No ano que vem vai ter quatro pessoas de novo, porque a minha prima do interior vem morar com a gente. Quando eu tenho saudade do meu pai, peço pra minha mãe falar dele.','egocentrico'),
    ('No alto das montanhas de um país chamado Paquistão, onde a estrada encontra a nascente do Rio de o ar é mais fresco, fica a cidade de Mingora, a maior do vale do swat. Foi lá que uma menina chamada Malala nasceu, em um casebre na frente da escola Khushal, do professor Ziuaddin Yousafzai, seu pai.','socializado'),
    ('Os talibãs tentaram calar Malala. Mas, em vez disso, a voz dela se tornou ainda mais forte, pois muitas pessoas se uniram à sua luta. E as meninas ficaram com mais vontade de estudar.','intermediario'),
    ('E Malala voltou a sorrir, porque era só uma menina que queria ir para a escola.','intermediario'),
    ('O menino ganhou um gato. Era um gato muito engraçado. E o mais engraçado do gato era que ele pensava que fosse francês.','intermediario'),
    ('O menino ganhou outro gato, o mais engraçado de todos. Um gato chinês muito carinhoso que vivia se enroscando no pescoço do menino e gostava de se deitar com a barriga pra cima esperando cafuné.','intermediario'),
    ('O menino pensou que estivesse sonhando. Um gato que dizia: “Miau”! Finalmente os gatos poderiam se entender.','socializado'),
    ('Era uma vez uma bicicleta e uma pipa que eram muito amigas. Sempre que a bicicleta saia pedalando, a pipa saía por aí empinando junto.','socializado'),
    ('Então a pipa olhou em volta, viu todas as outras e teve uma ideia. Ela foi passando perto das outras pipas e cochichando no ouvido de cada uma. Até que, aos poucos, aconteceu uma coisa incrível! As pipas foram se juntando num círculo e criando um redemoinho no céu, que nem a água do ralo, no fundo da banheira.','socializado'),
    ('Nesse dia a bicicleta ficou muito contente. Ela não sabia voar, mas enquanto tivesse uma amiga que nem a pipa, sempre que ela quisesse, podia ir pedalar lá no alto do céu.','intermediario'),
    ('O menino gostava muito de dormir no escuro com a janela aberta. Ele via os aviões passando, as nuvens, as estrelas e a lua, sua grande paixão. Só quando tinha raio ele tinha medo e fechava a janela.','intermediário'),
    ('Numa noite, todos dormiam, ele foi colocar a mochila e reparou que tinha um botão vermelho dentro do abajur. O que será? Curioso, apertou.','intermediario'),
    ('Naquela noite, o menino olhou da janela e parecia que a lua estava enorme, iluminada e sorrindo para ele.','intermediário'),
    ('Era uma vez em um reino distante, isolado entre montanhas e terra seca, e perdido no tempo… nesse lugar, as meninas não podiam ser vistas e eram proibidas de fazer tudo! Estudar, brincar, passear…','intermediario'),
    ('Sadaf tirou do baú as luvas de boxe escondidas desde que começou a gostar de brincar de luta e assustou os dragões: eles não esperavam meninas que lutavam boxe!','socializado'),
    ('Assim, venceram a guerra. E os meninos puderam voltar a plantar rosas na terra agora fértil. Porque, nesse reino distante, os meninos aprendiam cedo a guerrear, mas o que gostavam mesmo de fazer era cultivar rosas e colorir o céu com pipas.','intermediario'),
    ('Ela acordou cedo e desceu da cama baixinha. Primeiro deu bom dia ao dinossauro de pelúcia num abraço bem comprido. Depois apagou o abajur do quarto, pois o sol já iluminava o dia. Calçou as pantufas e foi chamar a mãe.','egocentrico'),
    ('E lá se foi à escola daquele jeito tão diferente. No começo a professora e os coleguinhas acharam engraçado aquele cabelo cheio de vírgulas, mas ela nem se importou.','intermediario'),
    ('Então as duas se abraçaram e cantaram juntas, rodopiando descabeladas pela sala.','intermediario'),
    ('Preciso fugir daqui, mas sei que não posso. Acho também que não devo fazer isso. Ou será que devo? Sem saber o que fazer, me lembro de um caderno de notas que eu trouxe na mochila. Ela está bem ao meu lado. Eu a pego. Meu caderno tem as páginas em branco. Meu caderno também é um prisioneiro: está preso ao silêncio de suas páginas vazias. Um caderno só fala quando escrevemos nele. Logo entendo que meu caderno me pede para escrever.','egocentrico'),
    ('Eu não acredito que a gente está na estrada. Não acredito. Eu vou acordar, eu vou acordar, eu vou acordar...Não acordei. E paramos num posto na estrada. Não vou comer nada, não vou comer, não quero. Não vou comer mais, nunca mais. Minha mãe me olha e eu acho que ela está desesperada. Mas não estava desesperada quando decidiu fazer isso comigo, me abandonar. Viajar para me abandonar. Não é viagem, é um engano, e não existe ninguém para me defender.','egocentrico'),
    ('Quadradinha de papel e fininho de papel são irmãos inseparáveis. Vivem brincando, dançando e se escondendo das enormes asas do vento.','socializado'),
    ('Quadradinha voa tanto, mas tanto, que fica muuuiiito cansada. Então ela resolve dormir um pouco,planando feito uma pluma de pavão. Quadradinha cerra os olhos e,agora sem medo, se deixa levar pelas asas do vento. Embalada pela canção das estrelas e da lua, Quadradinha viaja no sono gostoso','socializado'),
    ('Flora mora na fazenda e aprendeu a observar a natureza e a olhar para o céu e para os animais, lá no campo','socializado'),
    ('Vaca mimosa, que bela, que linda! Tem quatro pernas, pernas de vaca.','socializado')
    
    
    ]

    test = [
        ('Em um dia não inesperado na cidade chamada Cidade das Maravilhas chegou uma bruxa, e ela se fantasiou. Se transformou em uma mocinha comum da cidade. Aí em vez dela morar na cidade ela foi morar atrás da cidade , onde tinha uma floresta. Lá tinham muitos bichos, ela cuidou desses bichos. Ai teve uma festa para comemorar os 50 anos da cidade. Ai a bruxa resolveu ir nessa festa. Aí a festa tava rolando ai ela foi no banheiro ai trancou a porta, verificou se não tinha ninguém no banheiro mas ela esqueceu de verificar a última porta, aí já estava na hora dela tomar a poção mágica de novo para continuar se parecendo uma menina comum. Então ela não tomou e virou uma bruxa de novo.  A menininha então saiu do banheiro e viu que ela era uma bruxa. A menininha saiu correndo antes que a bruxa pudesse falar qualquer coisa. A bruxa correu pra casa dela na floresta. Depois de uma semana a cidade toda foi na Floresta aí viu que tinha uma casa igual casa de bruxa, a bruxa olhou pela janela. Todo mundo tinha levado comida como se fosse uma festa. A bruxa desceu e eles viram que a bruxa era boazinha. Mas mesmo sendo boazinha, era uma bruxa. Ela se deu bem com todo mundo. Fez vários amigos. E foi morar na cidade com seus novos amigos, mas continuou indo na floresta pra cuidar dos bichos. Ela viveu para sempre feliz com os amigos e com os bichos.', 'socializado'),
        ('enhum dia normal  o caverao entrou atirando para todos os lados sendo que pegou uma bala nem um menino sendo que ele ficou chorando muito ai foi os moradores pegaram ele e levou para o hospital  sendo que ele foi fazer uma serugia na perna segundo depois ele teve vicita ai os amigos dele foi ver ele amigo dele respondeue ai como foi ele respondeu foi tudo normal semanas depois ele foi para casa com ferro na perna a mae dele ficou muito feliz com ele pq ele saiu salvo do hospital ele ficou um pouco triste pq ele não pode corre mas vai passa tudo certo depois ele vai ta na rua brincando', 'intermediario')
    ]


    cl = NaiveBayesClassifier(train)
    
    


    resultado = cl.classify(texto)
    #acuracia = cl.accuracy(test)
    jab =Jabuti()
    jab.id_pessoa=id_pessoa
    jab.resultado=resultado
    jab.fase_processamento=fase
    jab.cadTxJabuti()

   # print (resultado)
   # print (cl.accuracy(test))
   # print (acuracia)
